### ISSUE TITLE
Samples don't compile

### ISSUE THREAD

**Issue by DanielSokil** [neutrinog/prism#1]
I tried running `game.cr`:
got error:
```bash
cc: error: /home/danielsokil/Desktop/Lab/Crystal/prism/src/crystglut/lib_gluc/libfreeglut_context.a: No such file or directory
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/danielsokil/.cache/crystal/crystal-run-game.tmp'  -rdynamic  /home/danielsokil/Desktop/Lab/Crystal/prism/src/crystglut/lib_gluc/libfreeglut_context.a -lglut -lGL -lpcre -lm -lgc -lpthread /usr/share/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

And `blank_window.cr`
error:
```bash
Error in samples/blank_window.cr:12: undefined constant Prism::Window

  window = Prism::Window.new(WIDTH, HEIGHT, TITLE)
```

Crystal info
```bash
$ crystal -v
Crystal 0.26.0 [eeb53c506] (2018-08-09)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by neutrinog** [comment]
Hey @DanielSokil, make sure you've installed freeglut and opengl. I'll write up some documentation on how to set up a development environment and contribute soon. I only just started this project last week and didn't expect to get any interest so soon.

FYI. I'm following this tutorial on how to build a game engine https://www.youtube.com/watch?v=ss3AnSxJ2X8&list=PLEETnX-uPtBXP_B2yupUKlflXBznWIlL5&index=1. I'm currently debugging `mesh.cr`, but if you want to see some output in the example you can un-comment the code in the `game.cr` render method.

**Comment by DanielSokil** [comment]
Thanks for the update!

**Comment by DanielSokil** [comment]
Also what do you mean by `Cross platform UI toolkit/Engine written in Crystal`? Crystal does not fully support the Windows platform.

**Comment by neutrinog** [comment]
Oops I totally missed that part. I just heard about crystal 2 weeks ago.
Thanks for the heads up.
