### ISSUE TITLE
Sample app too complex

### ISSUE THREAD

**Issue by alex-lairan** [neutrinog/prism#18]
Hi !

Thanks for your awesome job here !

I'm not a game developer, but I wanted to try obj import, so searched in your source code and in your sample app.

I tried this kind of code : 

```crystal
require "prism"
require "lib_gl"

class TestGame < Prism::Game
  def initialize
    super()
  end

  def init
    puts "Init the game"

    mesh = Prism::Mesh.new("media/statue.obj")
    mat  = Prism::Material.new

    obj = Prism::MeshRenderer.new(mesh, mat)

    shader = Prism::Shader.new("forward-ambient")
    render_engine = Prism::RenderingEngine.new

    camera = Prism::Camera.new(Prism.to_rad(0.0f32), 1920.0f32 / 1080.0f32, 0.01f32, 1000.0f32)
    render_engine.add_camera(camera)

    obj.render(shader, render_engine)
  end
end

engine = Prism::CoreEngine.new(1920, 1080, 60.0, "3D Game Engine", TestGame.new())
engine.start
``` 

Examples like this (but working) would help to enter.

:smile:

**Comment by neutrinog** [comment]
@alex-lairan I like it!
The current sample app is a mess, and adding a few different samples with increasing levels of complexity would probably help a lot.
Eventually I'm going to move the sample game into a completely separate repo and just limit the samples here to rendering things and some simple camera controls.
